set_vicare_mode:
  target:
    entity:
      integration: vicare
      domain: climate
  fields:
    vicare_mode:
      required: true
      selector:
        select:
          options:
            - "dhw"
            - "dhwAndHeating"
            - "dhwAndHeatingCooling"
            - "forcedNormal"
            - "forcedReduced"
            - "heating"
            - "standby"

set_preset_mode:
  target:
    entity:
      integration: vicare
      domain: climate
  fields:
    preset_mode:
      required: true
      selector:
        select:
          options:
            - "comfort"
            - "eco"
            - "normal"
            - "reduced"
